document.write("<div class=\"menu\">");
document.write("		<ul class=\"dmx l\">");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/\">首页<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/muse.html\">缪斯星专区<\/a><\/li>");
document.write("			<li class=\"nav\">");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/animation.html\">动漫专区<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/movie.html\">影视专区<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/app.html\">软件专区<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/r18.html\">R18专区<\/a><\/li>");
document.write("	<\/div>");
