document.write("<br>");
document.write("    <div class=\"foot\">");
document.write("        <div class=\"footbg\">");
document.write("<a>© 2022 Bilibili<\/a>");
document.write("              <br>");
document.write("           <a>Copyright © 2014-2022 <a href=\" https:\/\/musestar-cloud.gitHub.io\">MUSESTAR<\/a> All Rights Reserved<\/a>");
document.write("		<br>");
document.write("<a href=\"https:\/\/icp.gov.moe\/?keyword=20220574\" target=\"_blank\">萌ICP备20220574号<\/a>");
document.write("		<br>");
document.write("<a href=\"https:\/\/afdian.net\/@musestarxota" target=\"_blank\">爱发电<\/a>");
document.write("		<br>");
document.write("           <a>缪斯星官方QQ群：750813427<\/a>");