document.write("<br>");
document.write("    <div class=\"foot\">");
document.write("        <div class=\"footbg\">");
document.write("<a>© 2022 Bilibili<\/a>");
document.write("              <br>");
document.write("           <a href=\" https:\/\/musestar-cloud.gitHub.io\">Copyright © 2014-2022 MUSESTAR All Rights Reserved<\/a>");
document.write("		<br>");
document.write("<a href=\"https:\/\/musestar-cloud.github.io\/icp.html\" target=\"_blank\">萌ICP备20220574号<\/a>");
document.write("		<br>");
document.write("<a href=\"https:\/\/musestar-cloud.github.io\/FAQ.html\" target=\"_blank\">投稿反馈<\/a>");
document.write("		<br>");
document.write("<a href=\"https:\/\/musestar-cloud.github.io\/payhtml\" target=\"_blank\">发电赞助<\/a>");
document.write("		<br>");
document.write("           <a href=\"https:\/\/jq.qq.com\/?_wv=1027&k=4A08XieB\" target=\"_blank\">缪斯星官方QQ群：750813427<\/a>");
document.write("		<br>");
document.write("<img alt=\"GitHub last commit\" src=\"https:\/\/img.shields.io\/github\/last-commit\/MUSESTAR-Cloud\/musestar-cloud.github.io\">");