document.write("    <div class=\"side r\">");
document.write("    <div class=\"firs l\">");
document.write("    <div class=\"dtit\">");
document.write("        <h2><u><a href=\"https:\/\/musestar-cloud.github.io\/pay.html\" target=\"_blank\">发电赞助<\/a><\/u>榜<\/h2>");
document.write("    <\/div>");
document.write("    <\/div>");
document.write("	<div class=\"tlist\">");
document.write("<li>");
document.write("                <a>小成通过爱发电赞助了10元<\/a>");
document.write("            <\/li>");
document.write("<li>");
document.write("                <a>麻油通过微信支付赞助了8元<\/a>");
document.write("            <\/li>");
document.write("<li>");
document.write("                <a>生草通过支付宝支付赞助了3.52元<\/a>");
document.write("            <\/li>");
document.write("<\/div>      ");
document.write("    <div class=\"side r\">");
document.write("    <div class=\"firs l\">");
document.write("    <div class=\"dtit\">");
document.write("        <h2>网站加载慢问题<\/h2>");
document.write("    <\/div>");
document.write("    <\/div>");
document.write("	<div class=\"tlist\">");
document.write("                <a>请连接VPN或使用“软件专区”中的“Watt Toolkit”加速“Github.io”<\/a>");
document.write("<\/div><\/div>      ");
