document.write("    <div class=\"side r\">");
document.write("    <div class=\"firs l\">");
document.write("    <div class=\"dtit\">");
document.write("        <h2><u><a href=\"https:\/\/musestar-cloud.github.io\/pay.html\" target=\"_blank\">发电赞助<\/a><\/u>榜<\/h2>");
document.write("    <\/div>");
document.write("    <\/div>");
document.write("	<div class=\"tlist\">");
document.write("<li>");
document.write("                <span>");
document.write("                    <a>6-08<\/a><\/span>");
document.write("                <a>小成支持了10元<\/a>");
document.write("            <\/li>");
document.write("<li>");
document.write("                <span>");
document.write("                    <a>6-08<\/a><\/span>");
document.write("                <a>麻油支持了8元<\/a>");
document.write("            <\/li>");
document.write("<li>");
document.write("                <span>");
document.write("                    <a>5-15<\/a><\/span>");
document.write("                <a>生草支持了1.52元<\/a>");
document.write("            <\/li>");
document.write("<\/div>      ");
document.write("    <div class=\"side r\">");
document.write("    <div class=\"firs l\">");
document.write("    <div class=\"dtit\">");
document.write("        <h2>网站加载慢问题<\/h2>");
document.write("    <\/div>");
document.write("    <\/div>");
document.write("	<div class=\"tlist\">");
document.write("                <a>请连接VPN或使用“软件专区”中的“Watt Toolkit”加速“Github.io”<\/a>");
document.write("<\/div><\/div>      ");
