document.write("	<div class=\"menu\">");
document.write("		<ul class=\"dmx l\">");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/\"><img src=\"https:\/\/musestar-cloud.github.io\/ms.ico\" width=\"25\" height=\"25\"><\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/\">首页<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/muse.html\">缪斯星专区<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/animation.html\">动漫专区<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/movie.html\">影视专区<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/app.html\">软件专区<\/a><\/li>");
document.write("			<li>");
document.write("				<a href=\"https:\/\/musestar-cloud.github.io\/xota.html\">站长主页<\/a><\/li>");
document.write("    <\/ul>");
document.write("<ul class=\"dme r\">");
document.write("			<li class=\"nav\">");
document.write("<a href=\"https:\/\/musestar-cloud.github.io\/pay.html\" target=\"_blank\">发电赞助<\/a>");
document.write("			<\/li>");
document.write("			<li>");
document.write("<a href=\"https:\/\/jq.qq.com\/?_wv=1027&k=4A08XieB\" target=\"_blank\">缪斯星官方QQ群：750813427<\/a>");
document.write("			<\/li>");
document.write("    <\/div>");
document.write("	<br>");