document.write(" <div class=\"blank\"><\/div>");
document.write("        <div class=\"botit\">");
document.write("          <h2>温馨提示<\/h2><\/div>");
document.write("        <div class=\"info\"><font size=\"5\" color=\"red\">请不要相信视频内的任何广告<\/font><\/div>");
document.write("        <div class=\"info\">如遇卡顿可尝试向后时移1-3秒<\/div>");
document.write("        <div class=\"info\">部分浏览器需手动开始播放视频<\/div>");
document.write("      <\/div>");
document.write("         <\/div>");
document.write("<br>");
document.write("    <div class=\"foot\">");
document.write("        <div class=\"footbg\">");
document.write("           <a href=\" https:\/\/musestar-cloud.gitHub.io\">Copyright © 2014-2022 MUSESTAR All Rights Reserved<\/a>");
document.write("<a href=\"https:\/\/musestar-cloud.github.io\/icp.html\" target=\"_blank\">萌ICP备20220574号<\/a><br>");
document.write("           <a target=\"_blank\">本站只提供WEB页面服务，本站不存储、不制作任何视频，不承担任何由于内容的合法性及健康性所引起的争议和法律责任。<\/a>");
document.write("		<br>");
document.write("<img alt=\"GitHub last commit\" src=\"https:\/\/img.shields.io\/github\/last-commit\/MUSESTAR-Cloud\/musestar-cloud.github.io\">");