document.write(" <div class=\"blank\"><\/div>");
document.write("        <div class=\"botit\">");
document.write("          <h2>温馨提示<\/h2><\/div>");
document.write("        <font size=\"10\"><div class=\"info\">请不要相信视频内的任何广告<\/div><\/font>");
document.write("        <div class=\"info\">如遇卡顿可尝试向后时移1-3秒<\/div>");
document.write("        <div class=\"info\">部分浏览器需手动开始播放视频<\/div>");
document.write("      <\/div>");
document.write("         <\/div>");
document.write("<br>");
document.write("    <div class=\"foot\">");
document.write("        <div class=\"footbg\">");
document.write("           <p>Copyright © 2014-2022 <a href=\" https:\/\/musestar-cloud.gitHub.io\">MUSESTAR<\/a> All Rights Reserved<\/p>");
document.write("<a href=\"https:\/\/icp.gov.moe\/?keyword=20220574\" target=\"_blank\">萌ICP备20220574号<\/a><br>");
document.write("<a href=\"https:\/\/afdian.net\/@musestarxota\" target=\"_blank\">爱发电<\/a>");
document.write("		<br>");
document.write("           <a>缪斯星官方QQ群：750813427<\/a>");