document.write("          <div class=\"main0\" id=\"main0\">");
document.write("            <div class=\"movurl\" style=\"display: block;\"><ul>");
document.write("	     <li>");
document.write("               <a href=\".\/01.html\" target=\"_self\">第1集<\/a>");
document.write("            <\/li>     ");
document.write("            <li>");
document.write("               <a href=\".\/02.html\" target=\"_self\">第2集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\".\/03.html\" target=\"_self\">第3集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\".\/04.html\" target=\"_self\">第4集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\".\/05.html\" target=\"_self\">第5集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\".\/06.html\" target=\"_self\">第6集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\".\/07.html\" target=\"_self\">第7集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\".\/08.html\" target=\"_self\">第8集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\".\/09.html\" target=\"_self\">第9集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\".\/10.html\" target=\"_self\">第10集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\".\/11.html\" target=\"_self\">第11集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\".\/12.html\" target=\"_self\">第12集<\/a>");
document.write("            <\/li>");
document.write("			<\/ul><\/div><div class=\"movurl\" style=\"display: none;\"><ul>");
document.write("	     <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/01.html\" target=\"_self\">第1集<\/a>");
document.write("            <\/li>     ");
document.write("            <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/02.html\" target=\"_self\">第2集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/03.html\" target=\"_self\">第3集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/04.html\" target=\"_self\">第4集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/05.html\" target=\"_self\">第5集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/06.html\" target=\"_self\">第6集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/07.html\" target=\"_self\">第7集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/08.html\" target=\"_self\">第8集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/09.html\" target=\"_self\">第9集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/10.html\" target=\"_self\">第10集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/11.html\" target=\"_self\">第11集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/12.html\" target=\"_self\">第12集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/13.html\" target=\"_self\">第13集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/14.html\" target=\"_self\">第14集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/15.html\" target=\"_self\">第15集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/16.html\" target=\"_self\">第16集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/17.html\" target=\"_self\">第17集<\/a>");
document.write("            <\/li>");
document.write("           <li>");
document.write("               <a href=\"https:\/\/musestar-cloud.github.io\/animation\/gjtxyjlzaz2\/18.html\" target=\"_self\">第18集<\/a>");
document.write("            <\/li>");
document.write("			<\/ul><\/div><div class=\"movurl\" style=\"display:none\">");
