document.write(	     li);
document.write(               a href=httpsmusestar-cloud.github.ioteleplaymoonknight01.html title=第1集 target=_self第1集a);
document.write(            li     );
document.write(           li);
document.write(               a href=httpsmusestar-cloud.github.ioteleplaymoonknight02.html title=第2集 target=_self第2集a);
document.write(            li);
document.write(           li);
document.write(               a href=httpsmusestar-cloud.github.ioteleplaymoonknight03.html title=第3集 target=_self第3集a);
document.write(            li);
document.write(           li);
document.write(               a href=httpsmusestar-cloud.github.ioteleplaymoonknight04.html title=第4集 target=_self第4集a);
document.write(            li);
document.write(           li);
document.write(               a href=httpsmusestar-cloud.github.ioteleplaymoonknight05.html title=第5集 target=_self第5集a);
document.write(            li);
document.write(           li);
document.write(               a href=httpsmusestar-cloud.github.ioteleplaymoonknight06.html title=第6集 target=_self第6集a);
document.write(            li);
